version: '3'

services:
  proxy:
    image: {{ images.proxy }}:latest
    container_name: proxy
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  consumer:
    image: {{ images.consumer }}:latest
    container_name: consumer
    environment:
      HCLOUD_TOKEN: "${HCLOUD_TOKEN}"

  react-fe:
    image: {{ images.react_fe }}:latest
    container_name: react-fe
    network_mode: host

  strapi-fe:
    image: {{ images.strapi_fe }}:latest
    container_name: strapi-fe
    network_mode: host

  strapi:
    image: {{ images.strapi_be }}:latest
    container_name: strapi-be
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD={{ mysql.strapi_pw }}
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_BUCKET_NAME=cloud-game-public
    network_mode: host