---
- name: Include vars of certbot.yml
  register: load_vars
  include_vars:
    file: "{{ item }}"
  with_items:
  - aws.yml

- name: Install Pip
  apt:
    pkg: python3-pip
    state: present
    update_cache: true

- name: Install aws cli
  pip:
    name: awscli
    # extra_args: --user

- name: Create .aws dir
  file:
    path: /root/.aws
    state: directory
    mode: '0755'

- name: Touch aws credentials file
  file:
    path: "{{ item }}"
    state: touch
    mode: '0755'
  with_items:
  - /root/.aws/config
  - /root/.aws/credentials

- name: write aws config into file
  shell: "echo '{{ config }}' > /root/.aws/config"
 
- name: write aws credentials into file
  shell: "echo '{{ credentials }}' > /root/.aws/credentials"