---
- name: Install required packages
  apt:
    pkg:
    - lib32gcc1
    state: present
    update_cache: true

- name: Install AWS CLI
  include: aws-cli.yml

- name: Install SteamCMD
  include: steamcmd.yml

- name: Create ark directory
  become_user: steam
  file:
    path: "{{ ark.folder }}"
    state: directory
    mode: '0755'

- name: Install ark server
  become_user: steam
  shell: "steamcmd +login anonymous +force_install_dir {{ ark.folder }} +app_update {{ ark.steamid }} +quit"

- name: Copy file with owner and permissions
  become_user: steam
  copy:
    src: server_start.sh
    dest: "{{ ark.folder }}/ShooterGame/Binaries/Linux/server_start.sh"
    owner: steam
    group: steam
    mode: u=rwx,g=r,o=r

- name: Copy start ark server file
  copy:
    src: start-ark-server.sh
    dest: /root/start-ark-server.sh
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Copy backup server script
  copy:
    src: backup-server.sh
    dest: /usr/bin/backup-server
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Create Backup cron
  cron:
    name: "backup and update ark"
    minute: "0"
    hour: "5"
    job: "/usr/bin/backup-server"
