---
- name: Install required packages
  apt:
    pkg:
    - unzip
    state: present
    update_cache: true


- name: Download AWS CLI archive
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /root/awscliv2.zip

- name: Unzip archive
  unarchive:
    src: /root/awscliv2.zip
    dest: /root

- name: Install cli
  command: /root/aws/install
  args:
    creates: /usr/local/bin/aws
