---
- name: Install common packages
  apt:
    pkg:
    - telnet
    - vim
    - tcpdump
    state: present
    update_cache: true

- name: Disallow password authentication
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Disallow root login
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh
