version: "3"

services:
  strapi:
    build:
      context: ./backend
    container_name: strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    links:
      - db:db
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  db:
    container_name: mysql
    platform: linux/amd64
    image: mysql:5.7.29
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi

  consumer:
    build:
      context: ./async-server-provisioner
      dockerfile: Dockerfile-dev
    container_name: consumer
    command: ["npm", "run", "watch"]
    links:
      - db:db
    environment:
      - MYSQL_HOST=db
      - TERRAFORM_PATH=/opt/terraform/02-game-server
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
    volumes:
      - ~/.aws:/root/.aws
      - ./async-server-provisioner:/usr/src/app
      - ./infrastructure/terraform:/opt/terraform
