---
- name: Certbot
  template:
    src: certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    mode: 775

- name: Create Certs for Domains
  shell: /usr/bin/certbot certonly --register-unsafely-without-email --dns-route53 -d {{ item }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/fullchain.pem
  loop: "{{ domains }}"
