FROM node:13.12-stretch as build

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY . .

FROM node:13.12-stretch

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

CMD ["npm", "start"]
