FROM node:24.21.0-bookworm-slim AS build

ARG ADMIN_URL=/
ENV ADMIN_URL=$ADMIN_URL

ARG SERVE_ADMIN_PANEL=false
ENV SERVE_ADMIN_PANEL=$SERVE_ADMIN_PANEL

ARG SERVER_URL=http://localhost:1337
ENV SERVER_URL=$SERVER_URL
ENV STRAPI_ADMIN_BACKEND_URL=$SERVER_URL

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build


FROM nginx:stable-alpine

ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL}
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}
ENV DD_VERSION=${DD_GIT_COMMIT_SHA}

RUN rm -Rf /usr/share/nginx/*

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
