FROM node:16.14-bullseye as build

ARG ADMIN_URL=http://localhost:1337/admin
ENV ADMIN_URL=$ADMIN_URL

ARG SERVER_URL=http://localhost:1337
ENV SERVER_URL=$SERVER_URL

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build


FROM nginx:1.17.9-alpine

RUN rm -Rf /usr/share/nginx/*

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
