FROM node:16.14-bullseye as build

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY backend/package.json .
COPY backend/package-lock.json .

RUN npm ci

COPY backend .

FROM node:16.14-bullseye

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

CMD ["npm", "start"]
