FROM node:21.7-bullseye-slim

ENV NODE_ENV=development
WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y curl wget unzip \
    && curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh \
    && chmod +x install-opentofu.sh \
    && ./install-opentofu.sh --install-method deb \
    && wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.0/terragrunt_linux_amd64 -O /usr/bin/terragrunt \
    && chmod +x /usr/bin/terragrunt

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .
RUN npm run build

CMD ["npm", "run", "watch"]
