---
- name: Create game server watcher config
  template:
    src: game-server-watcher.yaml
    dest: /opt/game-server-watcher.yaml
    owner: root
    group: root

- name: Create game server watcher service
  template:
    src: game-server-watcher.service
    dest: /etc/systemd/system/game-server-watcher.service
    owner: root
    group: root

- name: Start game server watcher
  systemd:
    name: game-server-watcher
    daemon_reload: yes
    state: started
