---
- include_tasks: ../../../generic/bucket.yaml
- name: Find latest backup
  shell: aws s3 ls s3://{{ server.backup_s3_bucket }}/{{ backup_folder_path.stdout }} --page-size 1000 | awk '{print $4}' | sort | tail -n 1
  register: backup_key
- set_fact:
    backup_path: "{{ backup_folder_path.stdout }}{{ backup_key.stdout }}"
- name: "Debug print backup path"
  debug:
    msg: "{{ backup_path }}"
- name: Download backup
  amazon.aws.s3_object:
    bucket: "{{ server.backup_s3_bucket }}"
    object: "{{ backup_path }}"
    dest: /root/backup.tar.gz
    mode: get
  when: backup_key.stdout != ""
- name: Unzip archive
  unarchive:
    src: /root/backup.tar.gz
    dest: /mnt/backup/
  when: backup_key.stdout != ""
