---
- include_tasks: datadog.yml
  when: datadog.enabled
- include_tasks: game-server-watcher.yml

- name: Create mount path
  file:
    path: "/mnt/backup/"
    state: directory
    mode: "0777"
- include_tasks: fetch-backup.yml

- name: Fetch docker image
  shell: /usr/bin/docker pull {{ server.docker_image }}
- name: Create mount paths
  file:
    path: "/mnt/backup/{{ item.path }}"
    state: directory
    mode: "0777"
  loop: "{{ server.backup_paths }}"
- name: Create game-server systemd service
  template:
    src: game-server.service
    dest: /etc/systemd/system/game-server.service
    owner: root
    group: root
  notify: Start Game Server

- include_tasks: create-server-shutdown-service.yaml

- name: Reload Systmed
  systemd:
    daemon_reload: yes
