---
- include_tasks: datadog.yml
  when: datadog.enabled
- include_tasks: game-server-watcher.yml

- name: Fetch docker image
  shell: /usr/bin/docker pull {{ server.docker_image }}
- name: Create game-server systemd service
  template:
    src: game-server.service
    dest: /etc/systemd/system/game-server.service
    owner: root
    group: root
  notify: Start Game Server

- name: Reload Systmed
  systemd:
    daemon_reload: yes
