env: NODE_ENV
terraform_path: TERRAFORM_PATH
mysql:
  database: MYSQL_DATABASE
  host: MYSQL_HOST
  port: MYSQL_PORT
  user: MYSQL_USER
  pw: MYSQL_PW

hetzner:
  token: HCLOUD_TOKEN

hcloudServer:
  image: HCLOUD_IMAGE

datadog:
  enabled: DD_ENABLED
  api_key: DD_API_KEY

cloudGame:
  ansibleBranch: CLOUD_GAME_ANSIBLE_BRANCH
  apiUrl: CLOUD_GAME_API_URL
  apiToken: CLOUD_GAME_API_TOKEN
  backupS3Bucket: CLOUD_GAME_BACKUP_S3_BUCKET
