terraform_path: TERRAFORM_PATH
mysql:
  database: MYSQL_DATABASE
  host: MYSQL_HOST
  port: MYSQL_PORT
  user: MYSQL_USER
  pw: MYSQL_PW

hetzner:
  token: HCLOUD_TOKEN
  image: HCLOUD_IMAGE

datadog:
  enabled: DD_ENABLED
  api_key: DD_API_KEY
