env: dev
terraform_path: ./terraform/02-game-server
mysql:
  database: strapi
  host: 127.0.0.1
  port: 3306
  user: strapi
  pw: strapi

hetzner:
  token: placeholder

hcloudServer:
  type: cx31
  image: '162785630'
  location: nbg1

datadog:
  enabled: false
  api_key: placeholder

cloudGame:
  ansibleBranch: use-latest-backup
  apiUrl: http://host.docker.internal:1337
  apiToken: placeholder
  backupS3Bucket: cloud-game-dev
