terraform_path: ./terraform/02-game-server
mysql:
  database: strapi
  host: 127.0.0.1
  port: 3306
  user: strapi
  pw: strapi

hetzner:
  token: placeholder

hcloudServer:
  type: cx31
  image: '30619825'
  location: nbg1
