/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */

import blueprint from "@qkix/strapi-plugin-blueprint/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    blueprint: blueprint,
    graphql: graphql,
    "users-permissions": usersPermissions,
  },
});
