services:
  proxy:
    image: {{ images.proxy }}:latest
    container_name: proxy
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  consumer:
    image: {{ images.consumer }}:latest
    container_name: consumer
    network_mode: host
    environment:
      - "HCLOUD_TOKEN=${HCLOUD_TOKEN}"
      - NODE_ENV=production
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=strapi
      - MYSQL_USER=strapi
      - MYSQL_PW={{ mysql.strapi_pw }}
      - AWS_ACCESS_KEY_ID={{ consumer.access_key_id }}
      - AWS_SECRET_ACCESS_KEY={{ consumer.secret_access_key }}

  react-fe:
    image: {{ images.react_fe }}:latest
    container_name: react-fe
    network_mode: host

  strapi-fe:
    image: {{ images.strapi_fe }}:latest
    container_name: strapi-fe
    network_mode: host

  strapi:
    image: {{ images.strapi_be }}:latest
    container_name: strapi-be
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD={{ mysql.strapi_pw }}
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_BUCKET_NAME=cloud-game-public
    network_mode: host
