name: Game Server Watcher
args:
  - address:
      long: address
      help: IP address to serve on
      takes_value: true
      required: false
      default_value: 127.0.0.1
  - port:
      long: port
      help: Port on which the Webserver will listen
      takes_value: true
      required: true
  - base-url:
      long: base-url
      help: The base URL used to construct json links
      takes_value: true
      required: false
      default_value: http://127.0.0.1:8080
  - config-path:
      short: config
      long: config-path
      value_name: config-path
      help: Path to the configuration file.
      takes_value: true
      required: true
  - verbosity:
      short: v
      long: verbosity
      help: Log level verbosity.
      takes_value: true
      possible_values:
        - debug
        - info
        - warn
        - error
      default_value: info
