---
- name: Shutdown Game Server
  systemd:
    state: stopped
    name: game-server

- name: Generate Backup name
  shell: echo "backup-$(date +"%Y-%m-%d_%H_%M_%S").tar.gz"
  register: backup_name

- name: Archive Game Files
  archive:
    format: gz
    path: /root/game-server
    dest: /tmp/{{ backup_name.stdout.0 }}
