---
- set_fact:
    game_config: "{{ configuration | from_json }}"

- name: Install required packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - wget
    - dirmngr
    - gnupg
    - software-properties-common
    - python-pip
    state: present
    update_cache: true

- name: Add Java GPG apt Key
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present

- name: Add Java Repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
    state: present
    filename: java

- name: Install required packages
  apt:
    pkg:
    - "{{ item }}"
    state: present
    update_cache: true
    loop: "{{ game_config.server.packages }}"
