---
- name: Install Java
  include: java.yml

- set_fact:
    game_config: "{{ configuration | from_json }}"

- name: Ensure boto and boto3 modules are installed
  pip:
    name:
      - boto3
      - botocore

- name: Get latest backup
  shell: /usr/local/bin/aws s3 ls s3://{{ bucket_name }}/{{ base_path }}/ | grep 'backup-' | tail -n 1 | awk '{print $4}'
  register: latest_backup

- name: Download latest backup from S3
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    object: /{{base_path}}/{{ latest_backup.stdout_lines.0 }}
    dest: /root/backup.tar.gz
    mode: get

- name: Create Minecraft DIR
  file:
    path: /root/game-server
    state: directory

- name: Unpack Minecraft backup
  unarchive:
    src: /root/backup.tar.gz
    dest: /root/game-server

- name: Create Log Folder
  file:
    path: /var/log/game-server
    state: directory
    owner: root
    group: root

- name: Create Server Startup file
  template:
    src: startup.sh.j2
    dest: /root/startup.sh
    owner: root
    group: root
    mode: 0755

- name: Create shutdown service
  template:
    src: game-server-shutdown.service
    dest: /etc/systemd/system/gs-shutdown.service
    owner: root
    group: root
  notify: Start Game Server shutdown script

- name: Create Game Server systemd file
  template:
    src: game-server.service
    dest: /etc/systemd/system/game-server.service
    owner: root
    group: root
  notify: Start Game Server

- name: Just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
