on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/consumer.yml'
      - '.github/scripts/auth.sh'
      - '.github/scripts/deploy.sh'
      - 'async-server-provisioner/*'
      - 'async-server-provisioner/*/*'
      - 'async-server-provisioner/*/*/*'
      - 'async-server-provisioner/*/*/*/*'
      - 'async-server-provisioner/*/*/*/*/*'

name: Cloud Game Consumer

jobs:
  build:
    name: Build Consumer
    runs-on: ubuntu-latest
    env:
      IMAGE: 220002198733.dkr.ecr.eu-central-1.amazonaws.com/cloud-game/consumer
    steps:
      - uses: actions/checkout@master
      - name: Authenticate
        # if: github.ref == 'refs/heads/master'
        run: ./.github/scripts/auth.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          ECR_ACCOUNT: 220002198733.dkr.ecr.eu-central-1.amazonaws.com
      - name: Build Docker Container
        run: |
          docker build -t $IMAGE:$GITHUB_RUN_ID -f async-server-provisioner/Dockerfile .
      - name: Push Container
        run: |
          docker tag $IMAGE:$GITHUB_RUN_ID $IMAGE:latest
          docker push $IMAGE:$GITHUB_RUN_ID
          docker push $IMAGE:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Server
        env:
          DEPLOY_SSH_PRIV_KEY: ${{ secrets.DEPLOY_SSH_PRIV_KEY }}
        run: ./.github/scripts/deploy.sh