on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/consumer.yml"
      - ".github/scripts/auth.sh"
      - ".github/scripts/deploy.sh"
      - "async-server-provisioner/*"
      - "async-server-provisioner/*/*"
      - "async-server-provisioner/*/*/*"
      - "async-server-provisioner/*/*/*/*"
      - "async-server-provisioner/*/*/*/*/*"
      - "infrastructure/terraform/02-game-server/**/*"

name: Cloud Game Consumer

jobs:
  build:
    name: Build Consumer
    runs-on: ubuntu-latest
    env:
      IMAGE: cloudgame/async-server-provisioner
    steps:
      - uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Container
        run: |
          docker build -t $IMAGE:$GITHUB_RUN_ID -f async-server-provisioner/Dockerfile --build-arg DD_GIT_REPOSITORY_URL=$(git config --get remote.origin.url) --build-arg DD_GIT_COMMIT_SHADD_GIT_COMMIT_SHA=${{ github.sha }} .
      - name: Push Container
        run: |
          docker tag $IMAGE:$GITHUB_RUN_ID $IMAGE:latest
          docker push $IMAGE:$GITHUB_RUN_ID
          docker push $IMAGE:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Server
        env:
          DEPLOY_SSH_PRIV_KEY: ${{ secrets.DEPLOY_SSH_PRIV_KEY }}
        run: ./.github/scripts/deploy.sh
