on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Minecraft Backend Strapi

jobs:
  build-backend:
    name: Build Strapi API
    runs-on: ubuntu-latest
    env:
      IMAGE: 220002198733.dkr.ecr.eu-central-1.amazonaws.com/minecraft/backend:latest
    steps:
      - uses: actions/checkout@master
      - name: Authenticate
        # if: github.ref == 'refs/heads/master'
        run: ./.github/scripts/auth.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          ECR_ACCOUNT: 220002198733.dkr.ecr.eu-central-1.amazonaws.com
      - name: Build Docker Container
        run: |
          cd backend
          docker build -t $IMAGE -f Dockerfile-prod-be .
      - name: Push Container
        run: |
          docker push $IMAGE